chore: Use iab as cache prefix
ietf-tools/www pull request #412
Opened 2024-04-08 10:10 UTC by microamp

Found one minor discrepancy when diffing against the previous prod config.

2024-04-08 11:59 UTC, kesara requested changes

2024-04-08 20:18 UTC, microamp commented on helm/local.py
> +        "KEY_PREFIX": "iab",
Understood. Probably not worth a new release. I find `ietf` generic enough (for both sites). Will be revisited otherwise.

2024-04-08 20:18 UTC, closed without merging

2024-04-09 14:08 UTC, rjsparks commented
Why do you expect sharing a key prefix to be safe in this case? What's the other thing going into key generation that's guaranteed to avoid key collisions between the two wagtail instances?
See https://github.com/django/django/blob/ca5cd3e3e8e53f15e68ccd727ec8fe719cc48099/django/core/cache/backends/base.py#L32-L40 - I think it's pretty likely that wagtail itself would be generating the same prefixes for things it would want to cache? Or does wagtail go out of its way to ensure the prefix is unique based on the config? (If so, point to the code that does so?)

2024-04-09 14:11 UTC, rjsparks commented
(It may not matter as long as you guarantee that the ietf.org and iab.org instances are not sharing an instance of memcached, but if we ever were to put these back on one big host...)

2024-04-09 17:57 UTC, kesara commented
> (It may not matter as long as you guarantee that the ietf.org and iab.org instances are not sharing an instance of memcached, but if we ever were to put these back on one big host...)

Yeah, separation was the reason. Even on ietfa, the two sites did not share a single Memcached instance.
But if we think they might share a single Memcache db, we should use the Helm variable for that.