chore: Capture Nginx and Gunicorn logs in stdout
ietf-tools/www pull request #434
Opened 2024-04-23 04:11 UTC by microamp

Fixes #432 

I can see both Nginx and Gunicorn logs when I run `kubectl logs -f` locally now.

```text
127.0.0.1 - - [23/Apr/2024:04:23:57 +0100] "GET /healthz HTTP/1.0" 200 2 "-" "kube-probe/1.28" "10.244.0.1"
127.0.0.1 - - [23/Apr/2024:04:23:57 +0100] "GET /healthz HTTP/1.0" 200 2 "-" "kube-probe/1.28" "10.244.0.1"
10.244.0.1 - - [23/Apr/2024:03:23:57 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.28"
10.244.0.1 - - [23/Apr/2024:03:23:57 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.28"
127.0.0.1 - - [23/Apr/2024:04:24:06 +0100] "GET / HTTP/1.0" 200 30624 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "127.0.0.1"
127.0.0.1 - - [23/Apr/2024:03:24:06 +0000] "GET / HTTP/1.1" 200 5552 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
127.0.0.1 - - [23/Apr/2024:03:24:06 +0000] "GET /static/dist/main.9949552e4686.css HTTP/1.1" 200 324461 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
127.0.0.1 - - [23/Apr/2024:03:24:06 +0000] "GET /static/img/youtube-icon.c20ebf0e90c8.svg HTTP/1.1" 200 930 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
```

However, I'm not sure about the second commit. Configuring the Grafana agent to read from a file path may be cleaner (e.g. `/var/log/nginx/access.log`). To be discussed further.

2024-04-23 20:20 UTC, NGPixel commented
Is it useful to send access logs to Loki though?

2024-04-23 20:33 UTC, NGPixel commented
Output should be in json format for easier tagging

2024-04-23 20:34 UTC, NGPixel requested changes
Output should be in json format for easier tagging

2024-04-23 20:44 UTC, microamp commented
> Output should be in json format for easier tagging

Currently as a separate ticket here, https://github.com/ietf-tools/www/issues/433, but happy to combine them

2024-04-24 09:15 UTC, microamp commented
Application logs are now in JSON format. e.g.
```json
{"remote_host": "127.0.0.1", "remote_logname": "-", "remote_user": "-", "timestamp": "[24/Apr/2024:10:04:55 +0100]", "request": "GET /announcements/ HTTP/1.0", "status_code": "200", "response_size": "37152", "referrer": "http://localhost:8080/announcements/reappointment-of-eliot-lear-as-independent-submission-editor/", "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36", "x_forwarded_for": "127.0.0.1"}
```

Pretty-printed:
```json
{
  "remote_host": "127.0.0.1",
  "remote_logname": "-",
  "remote_user": "-",
  "timestamp": "[24/Apr/2024:10:04:55 +0100]",
  "request": "GET /announcements/ HTTP/1.0",
  "status_code": "200",
  "response_size": "37152",
  "referrer": "http://localhost:8080/announcements/reappointment-of-eliot-lear-as-independent-submission-editor/",
  "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "x_forwarded_for": "127.0.0.1"
}
```

2024-04-24 09:20 UTC, microamp commented on docker/gunicorn.py
> +        "x_forwarded_for": "%({x-forwarded-for}i)s",
`"%({X-Forwarded-For}i)s"`

is now all lowercase, i.e.

`"%({x-forwarded-for}i)s"`

as per the official documentation

> Use lowercase for header and environment variable names, and put {...}x names inside %(...)s. For example:
>
> %({x-forwarded-for}i)s

https://docs.gunicorn.org/en/stable/settings.html#access-log-format

2024-05-05 23:30 UTC, microamp commented
@NGPixel Mind having another look when you can please?

2024-05-06 00:09 UTC, NGPixel approved these changes

2024-05-06 03:53 UTC, merged